blogs/api/urls.py
from blogs.api import views
from django.urls import path

urlpatterns = [
    path('list/', views.IndexData.as_view(), name='bloglistdata'),
    path('<int:pk>/', views.DetailData.as_view(), name='blogdetaildata'),
    path('<int:pk>/delete/', views.DeleteBlogData.as_view(), name='blogdeletedata'),
    path('create/', views.CreateBlogData.as_view(), name='blogcreatedata'),
    path('<int:pk>/update/', views.UpdateBlogData.as_view(), name='blogupdatedata'),
    path('comments/<int:blog_id>/list/', views.ListCommentData.as_view(), name='commentlistdata'),
    path('comments/<int:pk>/', views.DetailCommentData.as_view(), name='commentdetaildata'),
    path('comments/<int:pk>/delete/', views.DeleteCommentData.as_view(), name='commentdeletedata'),
    path('comments/<int:blog_id>/create/', views.CreateCommentData.as_view(), name='commentcreatedata'),
    path('comments/<int:pk>/update/', views.UpdateCommentData.as_view(), name='commentupdatedata'),
    path('tags/list/', views.ListTagData.as_view(), name='taglistdata'),
]

blogs/urls.py
from django.urls import path
from . import views

app_name = "blogs"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("createblog/", views.CreateBlogView.as_view(), name="createblog"),
    path("updateblog/<int:pk>", views.UpdateBlogView.as_view(), name="updateblog"),
    path("deleteblog/<int:pk>", views.DeleteBlogView.as_view(), name="deleteblog"),
    path("createcomment/<int:blog_id>", views.CreateCommentView.as_view(), name="createcomment"),
    path("updatecomment/<int:pk>", views.UpdateCommentView.as_view(), name="updatecomment"),
    path("deletecomment/<int:pk>", views.DeleteCommentView.as_view(), name="deletecomment"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("blogs/", include("blogs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('api/v1/blogs/', include('blogs.api.urls')),
    path('api/v1/accounts/', include('accounts.api.urls')),
]

blogs/models.py
from django.db import models
from accounts.models import User
# Create your models here.
    
class Tag(models.Model):
    name = models.CharField(max_length=20, help_text="Tag's name")
    created_on = models.DateTimeField(auto_now_add=True, help_text="Date of creation")

    def __str__(self):
        return self.name
    
class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_user")
    tag = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True, related_name="blog_tag")
    name = models.CharField(max_length=30, help_text="Blog's name")
    content = models.TextField(help_text="Blog's content")
    created_on = models.DateTimeField(auto_now_add=True, help_text="Date of creation")
    updated_on = models.DateTimeField(auto_now=True, help_text="Date of update", null=True)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment_user")
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comment_blog")
    content = models.TextField(help_text="Comment's content")
    created_on = models.DateTimeField(auto_now_add=True, help_text="Date of creation")
    updated_on = models.DateTimeField(auto_now=True, help_text="Date of update")

    def __str__(self):
        return self.content

blogs/api/views.py
from rest_framework import generics
from blogs.api.serializers import BlogSerializer, CommentSerializer, TagSerializer
from blogs.models import Blog, Comment, Tag
from blogs.permissions import IsAdminOrReadOnly, IsOwnerOrReadOnly
from rest_framework.permissions import IsAuthenticated
import requests


# Create your views here.

class IndexData(generics.ListAPIView):
    queryset = Blog.objects.order_by("-created_on")[:10]
    serializer_class = BlogSerializer
    
class DetailData(generics.RetrieveAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer

class CreateBlogData(generics.CreateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        blog_name = self.request.data['name']
        requests.post(url='https://notify-api.line.me/api/notify', data={'message':'A blog named \'{}\' is created.'.format(blog_name)} ,headers={'Authorization': 'Bearer {}'.format('kooGFjl6eNWki8IfGzUYEahCNRl2VKJmDvdc40qBnSd')})
        tagName = self.request.data.get('tag')
        tagObject = Tag.objects.get(name=tagName)
        return serializer.save(user = self.request.user, tag = tagObject)
    
class UpdateBlogData(generics.UpdateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = [IsAdminOrReadOnly | IsOwnerOrReadOnly] 

    def perform_update(self, serializer):
        tagName = self.request.data.get('tag')
        tagObject = Tag.objects.get(name=tagName)
        return serializer.save(tag = tagObject)

class DeleteBlogData(generics.DestroyAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = [IsAdminOrReadOnly | IsOwnerOrReadOnly] 

class ListCommentData(generics.ListAPIView):
    serializer_class = CommentSerializer

    def get_queryset(self):
        blog_id = self.kwargs.get('blog_id')
        return Comment.objects.filter(blog=blog_id)

class CreateCommentData(generics.CreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticated] 

    def perform_create(self, serializer):
        return serializer.save(blog_id = self.request.path.split("/")[5], user = self.request.user)

class UpdateCommentData(generics.UpdateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsOwnerOrReadOnly] 

class DeleteCommentData(generics.DestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAdminOrReadOnly | IsOwnerOrReadOnly] 

class DetailCommentData(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class ListTagData(generics.ListAPIView):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer

blogs/views.py
from django.views.generic import TemplateView


# Create your views here.

class IndexView(TemplateView):
    template_name = 'blogs/index.html'
    
class DetailView(TemplateView):
    template_name = 'blogs/detail.html'

class CreateBlogView(TemplateView):
    template_name = 'blogs/create.html'

class UpdateBlogView(TemplateView):
    template_name = 'blogs/update.html'

class DeleteBlogView(TemplateView):
    template_name = 'blogs/delete.html'

class CreateCommentView(TemplateView):
    template_name = 'comments/create.html'

class UpdateCommentView(TemplateView):
    template_name = 'comments/update.html'

class DeleteCommentView(TemplateView):
    template_name = 'comments/delete.html'

blogs/templates/blogs/create.html
<!DOCTYPE html>
<html>

<body>
    <form method="POST" action="" id="createForm">
        <div>
            <label>Name : </label>
            <input type="text" id="name">        
        </div>
        <div>
            <label>Tag: </label>
            <select id="tag">
            </select>
        </div>
        <div>
            <label>Content : </label>
            <textarea id="content"></textarea>
        </div>
        <div>
            <input type="submit">
        </div>
    </form>
</body>
<script>
    window.onload = () => {
        TagGet()
        const formEl = document.getElementById("createForm")
        formEl.addEventListener('submit', blogCreate);
    }
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function blogCreate(event) {
        event.preventDefault();

        const data = {
            comment_blog: [],
            name: document.getElementById('name').value,
            tag: document.getElementById('tag').value,            
            content: document.getElementById('content').value,
        };

        const jsonData = JSON.stringify(data);
        console.log(jsonData)

        fetch(`/api/v1/blogs/create/`, {
            method: 'post',
            headers:
            {
                "X-CSRFToken": getCookie('csrftoken'),
                'Content-Type': 'application/json',
            },
            body: jsonData
        })
            .then(response => {
                if (response.ok) {
                    window.location.href = 'http://127.0.0.1:8000/blogs';
                }
                else {
                    console.error('Error creating the blog:', response.status);
                }
            })
            .catch(error => console.error('Error fetching blogs:', error));
    }
    function TagGet() {
        fetch(`/api/v1/blogs/tags/list`)
            .then(response => response.json())
            .then(data => {
                let tagNode = document.getElementById('tag');
                console.log(data)

                data.forEach(tag => {
                    let option = document.createElement('option')
                    option.setAttribute('value', tag.name)
                    option.textContent = tag.name
                    tagNode.appendChild(option)
                }); 
            })
            .catch(error => console.error('Error fetching tags:', error));
    }

</script>

</html>

blogs/templates/blogs/delete.html
<!DOCTYPE html>
<html>

<body>
    <div>
        <p>Are you sure?</p>
        <button type="button" id="confirm">Confirm?</button>
        <a id="cancelRef"><button type="button" id="cancel">Cancel</button></a>
    </div>
</body>

<script>
    window.onload = () => {
    let cancelRef = document.getElementById("cancelRef");
    cancelRef.href = `http://127.0.0.1:8000/blogs/${window.location.pathname.split("/")[3]}`

    confirmEl = document.getElementById("confirm");

    confirmEl.addEventListener("click", blogDelete);
        blogGet()
    }

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    
    function blogGet() {
        fetch(`/api/v1/blogs/${window.location.pathname.split("/")[3]}`)
            .then(response => response.json())
            .then(data => {
                
            })
            .catch(error => console.error('Error fetching blogpets:', error));
    }

    function blogDelete() {
        fetch(`/api/v1/blogs/${window.location.pathname.split("/")[3]}/delete/`,
            {
                method: 'delete',
                headers:
                {
                    "X-CSRFToken": getCookie('csrftoken'),
                }
            })
            .then(response => {
                if (response.ok) {
                    window.location.href = 'http://127.0.0.1:8000/blogs';
                }
                else {
                    console.error('Error deleting the blog:', response.status);
                }
            })
            .catch(error => console.error('Error fetching blogs:', error));
    }
    </script>

</html>

blogs/templates/blogs/detail.html
<!DOCTYPE html>
<html>

<body>
    <ul>
        <li id="name">Topic: </li>
        <li id="tag">Tag: </li>
        <li id="user">Post by: </li>
        <li id="updated_on">Last Edit: </li>
        <li id="created_on">Created: </li>
        <li id="content">Content: </li>
    </ul>
    <a id="toDelete">
        <button id="deleteButton">Delete?</button>
    </a>
    <a id="toUpdate">
        <button id="updateButton">Update?</button>
    </a>
    <a id="toComment">
        <button id="commentButton">Comment?</button>
    </a>
    <a id="indexRef" href="http://127.0.0.1:8000/blogs/">
        <button type="button" id="index">Go back</button>
    </a>

    <div id="comment_section">
    
    </div>
</body>
<script>

    window.onload = () => {
        let refDelete = document.getElementById('toDelete');
        refDelete.setAttribute('href', `http://127.0.0.1:8000/blogs/deleteblog/${window.location.pathname.split("/")[2]}`);

        let refUpdate = document.getElementById('toUpdate');
        refUpdate.setAttribute('href', `http://127.0.0.1:8000/blogs/updateblog/${window.location.pathname.split("/")[2]}`);
        
        let refComment = document.getElementById('toComment');
        refComment.setAttribute('href', `http://127.0.0.1:8000/blogs/createcomment/${window.location.pathname.split("/")[2]}`);

        blogDetail()

        commentList()
    }
    function blogDetail() {
        fetch(`/api/v1/blogs/${window.location.pathname.split("/")[2]}`)
            .then(response => response.json())
            .then(data => {
                let name = document.getElementById('name');
                name.textContent += data.name

                let tag = document.getElementById('tag');
                tag.textContent += data.tag

                let user = document.getElementById('user');
                user.textContent += data.user

                let updated_on = document.getElementById('updated_on');
                updated_on.textContent += data.updated_on

                let created_on = document.getElementById('created_on');
                created_on.textContent += data.created_on

                let content = document.getElementById('content');
                content.textContent += data.content

            })
            .catch(error => console.error('Error fetching the blog:', error));
    }

    function commentList() {
        fetch(`/api/v1/blogs/comments/${window.location.pathname.split("/")[2]}/list`)
            .then(response => response.json())
            .then(data => {
                const comment_section = document.getElementById("comment_section");
                data.forEach(comment => {
                    let ulNode = document.createElement('ul')
                    let user = document.createElement('li');
                    let created_date = document.createElement('li');
                    let content = document.createElement('li');

                    let refCommentDelete = document.createElement('a');
                    let refCommentUpdate = document.createElement('a');
                    refCommentDelete.setAttribute('href', `http://127.0.0.1:8000/blogs/deletecomment/${comment.id}`);
                    refCommentUpdate.setAttribute('href', `http://127.0.0.1:8000/blogs/updatecomment/${comment.id}`);

                    let commentDelete = document.createElement('button');
                    let commentUpdate = document.createElement('button');
                    commentDelete.textContent = "Delete?"
                    commentUpdate.textContent = "Edit?"

                    user.textContent = "Commenter: "+ comment.user
                    created_date.textContent = "Created Date: "+ comment.created_on
                    content.textContent = "Content: "+ comment.content

                    ulNode.appendChild(user)
                    ulNode.appendChild(created_date)
                    ulNode.appendChild(content)

                    refCommentDelete.appendChild(commentDelete);
                    refCommentUpdate.appendChild(commentUpdate);
                    
                    ulNode.appendChild(refCommentDelete)
                    ulNode.appendChild(refCommentUpdate)

                    comment_section.appendChild(ulNode)
                });
            })
            .catch(error => console.error('Error fetching blogs:', error));
    }
</script>

</html>

blogs/templates/blogs/index.html
{% if user.is_authenticated %}
Hi {{ user.username }}!
<p></p>
<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Logout?">
</form>

<a href = "{% url 'blogs:createblog'%}">
    <button type="button">Write a blog!</button>
</a>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> |
  <a href="{% url 'accounts:signup' %}">Sign Up</a>
{% endif %}


{% if latest_blog_list %}
    <h1> The latest blogs! </h1>
    <ul>
        {% for blog in latest_blog_list %}
        <li><a href="{% url 'blogs:detail' blog.id %}"> {{blog.name}} </a></li>
        {% endfor %}
    </ul>

{% else %}
    <h1> There is no blog yet! </h1>
{% endif %}

blogs/templates/blogs/update.html
<!DOCTYPE html>
<html>

<body>
    <form method="POST" action="" id="updateForm">
        <div>
            <label>Name : </label>
            <input type="text" id="name">        
        </div>
        <div>
            <label>Tag: </label>
            <select id="tag">

            </select>
        </div>
        <div>
            <label>Content : </label>
            <textarea id="content"></textarea>
        </div>
        <div>
            <input type="submit">
        </div>
    </form>
    <a id="cancelRef"><button type="button" id="cancel">Cancel</button></a>
</body>
<script>
    window.onload = () => {

        let cancelRef = document.getElementById("cancelRef");
        cancelRef.href = `http://127.0.0.1:8000/blogs/${window.location.pathname.split("/")[3]}/`

        const formEl = document.getElementById("updateForm");
        formEl.addEventListener('submit', blogUpdate);
        TagGet()
        blogGet()
    }
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    
    function TagGet() {
        fetch(`/api/v1/blogs/tags/list`)
            .then(response => response.json())
            .then(data => {
                let tagNode = document.getElementById('tag');
                //console.log(data)

                data.forEach(tag => {
                    let option = document.createElement('option')
                    option.setAttribute('value', tag.name)
                    option.textContent = tag.name
                    tagNode.appendChild(option)
                }); 
            })
            .catch(error => console.error('Error fetching tags:', error));
    }

    function blogGet() {
        fetch(`/api/v1/blogs/${window.location.pathname.split("/")[3]}`)
            .then(response => response.json())
            .then(data => {
                console.log(data)
                let name = document.getElementById('name');
                name.value = data.name

                let tag = document.getElementById('tag');
                tag.value = data.tag

                let content = document.getElementById('content');
                content.value = data.content
            })
            .catch(error => console.error('Error fetching blogs:', error));
    }
    
    function blogUpdate(event) {
        event.preventDefault();

        const data = {
            comment_blog: [],
            name: document.getElementById('name').value,
            tag: document.getElementById('tag').value,            
            content: document.getElementById('content').value,
        };

        const jsonData = JSON.stringify(data);
        console.log(jsonData)
        fetch(`/api/v1/blogs/${window.location.pathname.split("/")[3]}/update/`, {
            method: 'put',
            headers:
            {
                "X-CSRFToken": getCookie('csrftoken'),
                'Content-Type': 'application/json',
            },
            body: jsonData
        })
            .then(response => {
                console.log(response)
                if (response.ok) {
                    window.location.href = `http://127.0.0.1:8000/blogs/${window.location.pathname.split("/")[3]}`;
                }
                else {
                    console.error('Error creating the blogpet:', response.status);
                }
            })
            .catch(error => console.error('Error fetching blogpets:', error));
    }
    
</script>

</html>